### ISSUE TITLE
No sound in phone calls

### ISSUE THREAD

**Issue by Naozumi520** [rlawoehd187/android_device_pantech_ef71#3]
Hi, I'm currently in Hongkong. The phone call doesn't have any sound. (both sides has no sound).
I don't know if it the telecommunication company's fault or something else, but i fix it by edited the build.prop.
Here what I did:
Replace the value "true" in the line "persist.vendor.audio.fluence.voicecall=true" to false

After rebooting the phone I can hear sound from the other side and the other side can hear me too.

**Comment by rlawoehd187** [comment]
Thank you.
I'm using it for testing, so I didn't know about the call problem.

Thanks for the report.
